name: Pylint

on: workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          # pylint $(git ls-files '*.py')
          lintfiles=$(git ls-files '*.py')
          echo "Files to be pylinted:"
          echo "$lintfiles"
          echo "$lintfiles" | xargs pylint -v
          echo "$lintfiles" | xargs pylint -r true -v
